<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>io.lumen</groupId>
    <artifactId>lumen-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <modules>
        <module>lumen-core</module>
        <module>lumen-context</module>
        <module>lumen-web</module>
        <module>lumen-web-thymeleaf</module>
        <module>lumen-web-mvc</module>
        <module>lumen-security</module>
        <module>lumen-aop</module>
        <module>lumen-data</module>
        <module>lumen-boot</module>
        <module>lumen-boot-starter</module>
        <module>lumen-boot-starter-web</module>
        <module>lumen-boot-starter-thymeleaf</module>
        <module>lumen-boot-starter-data-jpa</module>
        <module>lumen-boot-starter-security</module>
        <module>lumen-validation</module>
        <module>lumen-boot-starter-validation</module>
        <module>lumen-cache</module>
        <module>lumen-boot-starter-cache</module>
    </modules>
</project>